defaults:
  - model: lensless
  - writer: cometml
  - metrics: image_metrics
  - dataloader: inference
  - _self_

inferencer:
  device_tensors: ["lensless", "psf"]
  device: auto
  save_path: "inference_save"
  seed: 1
  model_weights: "model_weights_le_admm_pre_pro_inv.pth"

datasets:
  inference:
    _target_: src.datasets.CustomDirDataset
    path: inference_dataset

transforms:
  instance_transforms: {}
  batch_transforms: {}