defaults:
  - writer: cometml
  - datasets: digicam-test
  - metrics: image_metrics
  - dataloader: inference
  - _self_

model_name: "LeADMM-5-pre-post-inv"

inferencer:
  device_tensors: ["lensless", "psf"]
  device: auto
  save_path: "inference_save"
  seed: 1

transforms:
  instance_transforms: {}
  batch_transforms: {}